// Generated by the Tensor Algebra Compiler (tensor-compiler.org)
// /home/qxj/Workload-Aware-Co-Optimization/code_generator/taco/build/bin/taco 
// "A(i,j)=B(i,k)*C(k,j)" -f=A:dd:0,1 -f=B:ds:1,0 -f=C:dd:0,1 -write-compute=taco_kernel.c

int compute(taco_tensor_t *A, taco_tensor_t *B, taco_tensor_t *C, taco_tensor_t *Ad, taco_tensor_t *Bd, taco_tensor_t *Cd) {
  int A1_dimension = (int)(A->dimensions[0]);
  int A2_dimension = (int)(A->dimensions[1]);
  double* __restrict A_vals = (double*)(A->vals);
  int B2_dimension = (int)(B->dimensions[1]);
  int* __restrict B2_pos = (int*)(B->indices[1][0]);
  int* __restrict B2_crd = (int*)(B->indices[1][1]);
  double* __restrict B_vals = (double*)(B->vals);
  int C1_dimension = (int)(C->dimensions[0]);
  int C2_dimension = (int)(C->dimensions[1]);
  double* __restrict C_vals = (double*)(C->vals);

  for (int32_t k = 0; k < C1_dimension; k++) {
    for (int32_t iB = B2_pos[k]; iB < B2_pos[(k + 1)]; iB++) {
      int32_t i = B2_crd[iB];
      for (int32_t j = 0; j < C2_dimension; j++) {
        int32_t jA = i * A2_dimension + j;
        int32_t jC = k * C2_dimension + j;
        A_vals[jA] = A_vals[jA] + B_vals[iB] * C_vals[jC];
      }
    }
  }
  return 0;
}
